version: '3.8'
services:
  database:
    image: docker.io/library/postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=budget_db
    ports:
      - '5431:5432'