spring:
  application:
    name: budget
  datasource:
    url: "jdbc:postgresql://localhost:5431/budget_db"
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    user: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5431/budget_db"
    baselineOnMigrate: true
    cleanDisabled: false
    cleanOnValidationError: true
    baselineVersion: 1.1.0

app:
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5431/budget_db"
    username: postgres
    password: postgres
    maximum-pool-size: 10

api:
  security:
    token:
      secret: mySecret

jwt:
  cookie-expiration: 10800