spring:
  application:
    name: budget
  datasource:
    url: "jdbc:postgresql://localhost:5431/budget_db"
    username: yours
    password: yours
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
api:
  security:
    token:
      secret: secret
jwt:
  cookie-expiration: value