spring:
  application:
    name: budget
  datasource:
    url: "jdbc:postgresql://localhost:5431/budget_db"
    username: postgres
    password: postgres
  flyway:
    user: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5431/budget_db"
    baselineOnMigrate: true
    cleanDisabled: false
    cleanOnValidationError: true
app:
  datasource:
    jdbc-url: "jdbc:postgresql://localhost:5431/budget_db"
    username: postgres
    password: postgres
    maximum-pool-size: 10

api:
  security:
    token:
      secret: mySecret

jwt:
  cookie-expiration: 10800