CREATE TABLE IF NOT EXISTS "categories" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(60) NOT NULL
);

CREATE TABLE IF NOT EXISTS "boards" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "user_id" INT NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS "transactions" (
    "id" INT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(60) NOT NULL,
    "description" VARCHAR NOT NULL UNIQUE,
    "predicted_value" FLOAT,
    "actual_value" FLOAT,
    "due_date" DATE NOT NULL,
    "status" SMALLINT,
    "type" SMALLINT,
    "board_id" INT,
    CONSTRAINT fk_boards_transactions FOREIGN KEY(board_id) REFERENCES boards(id)
);

CREATE TABLE IF NOT EXISTS "categories_transactions" (
    "category_id" INT NOT NULL,
    "transaction_id" INT NOT NULL,
    CONSTRAINT fk_categories_transactions FOREIGN KEY(category_id) REFERENCES categories(id),
    CONSTRAINT fk_transactions_categories FOREIGN KEY(transaction_id) REFERENCES transactions(id)
);

